
const misc =
    [
        "",
        "Standard ",
        "Time",
        "Eastern ",
        "Central ",
        "Western ",
        "Pacific ",
        "Mountain ",
        "European ",
        "Australian ",
        "Timer",
        "Mushroom",
        "Box",
        "Start",
        "Ready",
        "Name",
        "Level",
        "Grow Time",
        "Substrates",
        "Phase Ready",
        "Show Box Timers!",
        "Show Phase Info!",
        "Now!",
        "Timer ",
        " day ",
        " days ",
        " hours",
        "en-US",
        "America/New_York",
        "_box-timer"
    ]
